export const MALAYALAM_PRODUCT_NAMES: Record<string, string> = {
  // --- Fresh Vegetables ---
  'veg tomato bangalore': 'ബാംഗ്ലൂർ തക്കാളി',
  'veg tomato country': 'നാടൻ തക്കാളി',
  'tomato bangalore': 'ബാംഗ്ലൂർ തക്കാളി',
  'tomato country': 'നാടൻ തക്കാളി',
  'tomato': 'തക്കാളി',
  'tomatoes': 'തക്കാളി',
  'local tomato': 'നാടൻ തക്കാളി',
  'country tomato': 'നാടൻ തക്കാളി',
  'veg onion kg': 'സവാള (വലിയ ഉള്ളി)',
  'veg sambar onion': 'ചെറിയ ഉള്ളി (സാമ്പാർ ഉള്ളി)',
  'sambar onion': 'ചെറിയ ഉള്ളി (സാമ്പാർ ഉള്ളി)',
  'onion': 'സവാള',
  'onions': 'സവാള',
  'big onion': 'സവാള',
  'small onion': 'ചെറിയ ഉള്ളി',
  'shallots': 'ചെറിയ ഉള്ളി',
  'shallot': 'ചെറിയ ഉള്ളി',
  'veg potato': 'ഉരുളക്കിഴങ്ങ്',
  'veg baby potato': 'ചെറിയ ഉരുളക്കിഴങ്ങ്',
  'baby potato': 'ചെറിയ ഉരുളക്കിഴങ്ങ്',
  'potato': 'ഉരുളക്കിഴങ്ങ്',
  'potatoes': 'ഉരുളക്കിഴങ്ങ്',
  'veg ladies finger': 'വെണ്ടയ്ക്ക',
  'ladies finger': 'വെണ്ടയ്ക്ക',
  'ladyfinger': 'വെണ്ടയ്ക്ക',
  'okra': 'വെണ്ടയ്ക്ക',
  'veg green chilli': 'പച്ചമുളക്',
  'green chilli': 'പച്ചമുളക്',
  'green chillies': 'പച്ചമുളക്',
  'gundu chilli green': 'ഗുണ്ടു മുളക്',
  'bajji capsicum': 'ബജ്ജി മുളക്',
  'veg bajji capsicum': 'ബജ്ജി മുളക്',
  'veg drumstick': 'മുരിങ്ങക്കായ',
  'drumstick': 'മുരിങ്ങക്കായ',
  'veg bitter gourd hybrid': 'പാവയ്ക്ക',
  'veg bitter gourd small': 'നാടൻ പാവയ്ക്ക (കൈപ്പക്ക)',
  'bitter gourd': 'പാവയ്ക്ക',
  'bittergourd': 'പാവയ്ക്ക',
  'veg bottle gourd': 'ചുരയ്ക്ക',
  'bottle gourd': 'ചുരയ്ക്ക',
  'bottlegourd': 'ചുരയ്ക്ക',
  'veg snake gourd': 'പടവലങ്ങ',
  'snake gourd': 'പടവലങ്ങ',
  'snakegourd': 'പടവലങ്ങ',
  'veg ash gourd': 'കുമ്പളങ്ങ',
  'ash gourd': 'കുമ്പളങ്ങ',
  'ashgourd': 'കുമ്പളങ്ങ',
  'veg country pumpkin': 'നാടൻ മത്തങ്ങ',
  'pumpkin': 'മത്തങ്ങ',
  'country pumpkin': 'നാടൻ മത്തങ്ങ',
  'veg ridge gourd': 'പീച്ചിങ്ങ',
  'ridge gourd': 'പീച്ചിങ്ങ',
  'veg coccinia': 'കോവയ്ക്ക',
  'coccinia': 'കോവയ്ക്ക',
  'tindora': 'കോവയ്ക്ക',
  'veg colocasia': 'ചേമ്പ്',
  'colocasia': 'ചേമ്പ്',
  'taro': 'ചേമ്പ്',
  'veg yam / karunaikizhangu': 'ചേന',
  'yam': 'ചേന',
  'elephant foot yam': 'ചേന',
  'veg tapioca roots': 'കപ്പ (മരച്ചീനി)',
  'tapioca': 'കപ്പ',
  'tapioca roots': 'കപ്പ',
  'cassava': 'കപ്പ',
  'veg raw banana': 'ഏത്തക്കായ (പച്ചക്കായ)',
  'raw banana': 'ഏത്തക്കായ (പച്ചക്കായ)',
  'plantain': 'പച്ചക്കായ',
  'veg raw mango': 'പച്ചമാങ്ങ',
  'raw mango': 'പച്ചമാങ്ങ',
  'veg broad beans': 'അമരക്ക',
  'broad beans': 'അമരക്ക',
  'veg cluster beans': 'കൊത്തമര',
  'cluster beans': 'കൊത്തമര',
  'veg cucumber country': 'നാടൻ വെള്ളരിക്ക',
  'veg cucumber malabar': 'കണിവെള്ളരി',
  'veg french cucumber': 'സാലഡ് വെള്ളരിക്ക',
  'crisp green cucumber': 'വെള്ളരിക്ക',
  'cucumber': 'വെള്ളരിക്ക',
  'cucumbers': 'വെള്ളരിക്ക',
  'veg french beans': 'ബീൻസ്',
  'french beans': 'ബീൻസ്',
  'beans': 'ബീൻസ്',
  'veg butter beans': 'ബട്ടർ ബീൻസ്',
  'butter beans': 'ബട്ടർ ബീൻസ്',
  'veg carrot': 'കാരറ്റ്',
  'carrot': 'കാരറ്റ്',
  'carrots': 'കാരറ്റ്',
  'veg beetroot': 'ബീറ്റ്‌റൂട്ട്',
  'beetroot': 'ബീറ്റ്‌റൂട്ട്',
  'veg cabbage': 'കാബേജ്',
  'cabbage': 'കാബേജ്',
  'veg chinese cabbage': 'ചൈനീസ് കാബേജ്',
  'chinese cabbage': 'ചൈനീസ് കാബേജ്',
  'veg cauliflower': 'കോളിഫ്ലവർ',
  'cauliflower': 'കോളിഫ്ലവർ',
  'veg broccoli': 'ബ്രോക്കോളി',
  'broccoli': 'ബ്രോക്കോളി',
  'veg capsicum green': 'പച്ച ക്യാപ്സിക്കം',
  'capsicum red': 'ചുവന്ന ക്യാപ്സിക്കം',
  'capsicum': 'ക്യാപ്സിക്കം',
  'veg garlic': 'വെളുത്തുള്ളി',
  'garlic': 'വെളുത്തുള്ളി',
  'veg ginger': 'ഇഞ്ചി',
  'ginger': 'ഇഞ്ചി',
  'fresh wayanad ginger': 'വയനാടൻ ഇഞ്ചി',
  'veg ginger mango': 'മാങ്ങാ ഇഞ്ചി',
  'mango ginger': 'മാങ്ങാ ഇഞ്ചി',
  'veg lemon': 'ചെറുനാരങ്ങ',
  'lemon': 'ചെറുനാരങ്ങ',
  'lime': 'ചെറുനാരങ്ങ',
  'veg curry leaves': 'കറിവേപ്പില',
  'curry leaves': 'കറിവേപ്പില',
  'curry leaf': 'കറിവേപ്പില',
  'veg coriander leaves': 'മല്ലിയില',
  'coriander leaves': 'മല്ലിയില',
  'coriander leaf': 'മല്ലിയില',
  'veg mint leaves': 'പുതിനയില',
  'mint leaves': 'പുതിനയില',
  'mint leaf': 'പുതിനയില',
  'mint': 'പുതിനയില',
  'veg greens moringa': 'മുരിങ്ങയില',
  'moringa leaves': 'മുരിങ്ങയില',
  'veg greens palak': 'പാലക് ചീര',
  'palak': 'പാലക് ചീര',
  'spinach': 'ചീര',
  'cheera': 'ചീര',
  'veg greens thandu keerai': 'തണ്ട് ചീര',
  'veg greens siru keerai': 'ചെറുചീര',
  'veg greens arai keerai': 'അരക്കീര',
  'veg greens akathi keerai': 'അഗത്തിച്ചീര',
  'veg greens ponnagkanni keerai': 'പൊന്നങ്കണ്ണി ചീര',
  'ponnakanni keerai': 'പൊന്നങ്കണ്ണി ചീര',
  'veg greens manathakali keerai': 'മണത്തക്കാളി ഇല',
  'veg greens fenugreek leaves': 'ഉലുവയില',
  'veg white radish': 'മുള്ളങ്കി',
  'radish': 'മുള്ളങ്കി',
  'white radish': 'മുള്ളങ്കി',
  'veg sweet potato': 'മധുരക്കിഴങ്ങ്',
  'sweet potato': 'മധുരക്കിഴങ്ങ്',
  'veg coconut small': 'തേങ്ങ',
  'coconut': 'തേങ്ങ',
  'veg banana flower': 'വാഴക്കൂമ്പ് (കുടപ്പൻ)',
  'banana flower': 'വാഴക്കൂമ്പ്',
  'veg banana stem': 'വാഴപ്പിണ്ടി',
  'banana stem': 'വാഴപ്പിണ്ടി',
  'veg banana leaf': 'വാഴയില',
  'banana leaf': 'വാഴയില',
  'veg brinjal ujala': 'നീളൻ വഴുതനങ്ങ',
  'veg brinjal vari': 'വരി വഴുതനങ്ങ',
  'brinjal round suphol': 'ഉരുണ്ട വഴുതനങ്ങ',
  'brinjal': 'വഴുതനങ്ങ',
  'eggplant': 'വഴുതനങ്ങ',
  'aubergine': 'വഴുതനങ്ങ',
  'veg knol khol': 'കോൾറാബി (Knol Khol)',
  'veg chow chow': 'ചൗ ചൗ',
  'chow chow': 'ചൗ ചൗ',
  'veg celery': 'സെലറി',
  'celery': 'സെലറി',
  'veg lettuce iceberg': 'ലെറ്റൂസ്',
  'lettuce': 'ലെറ്റൂസ്',
  'veg parsley': 'പാർസിലി',
  'parsley': 'പാർസിലി',
  'veg spring onion': 'സ്പ്രിംഗ് ഒനിയൻ (ഉള്ളിത്തണ്ട്)',
  'spring onion': 'സ്പ്രിംഗ് ഒനിയൻ (ഉള്ളിത്തണ്ട്)',
  'veg leeks': 'ലീക്സ്',
  'leeks': 'ലീക്സ്',
  'zucchini yellow': 'മഞ്ഞ സൂക്കിനി',
  'zucchini': 'സൂക്കിനി',
  'veg baby corn': 'ബേബി കോൺ',
  'baby corn': 'ബേബി കോൺ',
  'baby corn peeled': 'ബേബി കോൺ തൊലി കളഞ്ഞത്',
  'veg american sweet corn': 'സ്വീറ്റ് കോൺ (മധുരച്ചോളം)',
  'sweet corn': 'സ്വീറ്റ് കോൺ',
  'veg corn': 'ചോളം',
  'corn': 'ചോളം',
  'veg mushroom box': 'കൂൺ (Mushroom)',
  'mushrooms': 'കൂൺ',
  'mushroom': 'കൂൺ',
  'veg gooseberry amla': 'നെല്ലിക്ക',
  'gooseberry': 'നെല്ലിക്ക',
  'amla': 'നെല്ലിക്ക',
  'veg fresh groundnut': 'പച്ചക്കപ്പലണ്ടി',
  'fresh groundnut': 'പച്ചക്കപ്പലണ്ടി',
  'cow pea karamani / nadan payar': 'നാടൻ വൻപയർ (പയർ)',
  'soya beans': 'സോയാബീൻ',
  'soyabean': 'സോയാബീൻ',
  'pirandai / veldt grape': 'ചങ്ങലംപരണ്ട',
  'turmeric plant fresh': 'പച്ചമഞ്ഞൾ',
  'paraval': 'പടവലം (പോട്‌വൽ)',
  'parwal': 'പടവലം (പോട്‌വൽ)',
  'mahali kizhangu': 'മാഹളി കിഴങ്ങ്',
  'mahali potato': 'മാഹളി കിഴങ്ങ്',
  'mudavattukal kilangu': 'മുടവത്തു കാൽ കിഴങ്ങ്',
  'mudavattu kilangu': 'മുടവത്തു കാൽ കിഴങ്ങ്',

  // --- Fresh Fruits ---
  'banana nendran / ethan': 'നേന്ത്രപ്പഴം (ഏത്തപ്പഴം)',
  'nendran banana': 'നേന്ത്രപ്പഴം',
  'banana poovan': 'പൂവൻ പഴം',
  'poovan banana': 'പൂവൻ പഴം',
  'banana red': 'ചെങ്കദളി പഴം (ചുവന്ന പഴം)',
  'red banana': 'ചെങ്കദളി പഴം (കപ്പപ്പഴം)',
  'banana yelakki': 'ഞാലിപ്പൂവൻ പഴം',
  'yelakki banana': 'ഞാലിപ്പൂവൻ പഴം',
  'banana karpooravalli': 'കർപ്പൂരവള്ളി പഴം',
  'banana morris': 'റോബസ്റ്റ പഴം (മോറിസ്)',
  'robusta banana': 'റോബസ്റ്റ പഴം',
  'banana rasthali': 'രസകദളി പഴം',
  'banana green': 'പച്ചക്കായ',
  'banana hill': 'മലവാഴപ്പഴം (കുന്നൻ പഴം)',
  'banana': 'വാഴപ്പഴം',
  'bananas': 'വാഴപ്പഴം',
  'guava': 'പേരയ്ക്ക',
  'guava imported': 'പേരയ്ക്ക (ഇംപോർട്ടഡ്)',
  'papaya': 'പപ്പായ (കപ്പങ്ങ / ഓമക്ക)',
  'black grapes paneer': 'പനീർ മുന്തിരി (കറുത്ത മുന്തിരി)',
  'grapes red globe indian': 'റെഡ് ഗ്ലോബ് മുന്തിരി (ചുവന്ന മുന്തിരി)',
  'grapes': 'മുന്തിരി',
  'grape': 'മുന്തിരി',
  'black grapes': 'കറുത്ത മുന്തിരി',
  'green grapes': 'പച്ച മുന്തിരി',
  'apple shimla': 'ഷിംല ആപ്പിൾ',
  'apple fuji': 'ഫ്യൂജി ആപ്പിൾ',
  'apple royal gala': 'റോയൽ ഗാല ആപ്പിൾ',
  'apple red delicious': 'റെഡ് ഡെലീഷ്യസ് ആപ്പിൾ',
  'green apple': 'ഗ്രീൻ ആപ്പിൾ',
  'apple': 'ആപ്പിൾ',
  'apples': 'ആപ്പിൾ',
  'mosambi': 'മുസംബി (മധുരനാരങ്ങ)',
  'musk melon / mulampazham': 'ഷമാം (മുഴംപഴം)',
  'musk melon': 'ഷമാം',
  'watermelon': 'തണ്ണിമത്തൻ',
  'orange imported': 'ഓറഞ്ച്',
  'baby orange': 'ചെറിയ ഓറഞ്ച്',
  'orange': 'ഓറഞ്ച്',
  'oranges': 'ഓറഞ്ച്',
  'anjeer fruit': 'അത്തിപ്പഴം (Anjeer)',
  'anjeer': 'അത്തിപ്പഴം',
  'fig': 'അത്തിപ്പഴം',
  'indian plums': 'പ്ലംസ് (ഇന്ത്യൻ പ്ലം)',
  'plums': 'പ്ലംസ്',
  'country green pears': 'നാടൻ സബർജില്ലി (Green Pears)',
  'pear green howell': 'സബർജില്ലി (Green Pears)',
  'red pears': 'ചുവന്ന സബർജില്ലി (Red Pears)',
  'pears': 'സബർജില്ലി (Pears)',
  'pear': 'സബർജില്ലി',
  'kiwi': 'കിവി',
  'dragon fruit': 'ഡ്രാഗൺ ഫ്രൂട്ട്',
  'avocado': 'വെണ്ണപ്പഴം (Avocado)',
  'strawberry box': 'സ്ട്രോബെറി ബോക്സ്',
  'strawberry': 'സ്ട്രോബെറി',
  'blueberry box': 'ബ്ലൂബെറി ബോക്സ്',
  'blueberry': 'ബ്ലൂബെറി',
  'cherry': 'ചെറി (Cherry)',
  'cherries': 'ചെറി (Cherries)',
  'durian imported': 'ഡ്യൂറിയൻ പഴം',
  'durian': 'ഡ്യൂറിയൻ',
  'mango': 'മാമ്പഴം',
  'mangoes': 'മാമ്പഴം',
  'alphonso mango': 'അൽഫോൻസോ മാമ്പഴം',
  'pineapple': 'കൈതച്ചക്ക',
  'pomegranate': 'മാതളനാരങ്ങ (ഉറുമാമ്പഴം)',
  'jackfruit': 'ചക്ക',

  // --- Grains, Flours & Rice ---
  'matta rice': 'മട്ട അരി',
  'basmati rice': 'ബാസ്മതി അരി',
  'biryani rice': 'ബിരിയാണി അരി',
  'jeerakasala rice': 'ജീരകശാല അരി',
  'kaima rice': 'കൈമ അരി',
  'rice': 'അരി',
  'raw rice': 'പച്ചരി',
  'boiled rice': 'പുഴുങ്ങലരി',
  'white rice': 'വെള്ള അരി',
  'wheat': 'ഗോതമ്പ്',
  'broken wheat': 'ഗോതമ്പ് നുറുക്ക്',
  'atta': 'ആട്ട (ഗോതമ്പ് പൊടി)',
  'wheat flour': 'ഗോതമ്പ് പൊടി (ആട്ട)',
  'maida': 'മൈദ',
  'rava': 'റവ',
  'semolina': 'റവ',
  'sooji': 'റവ',
  'puttu podi': 'പുട്ടുപൊടി',
  'appam podi': 'അപ്പപ്പൊടി',
  'idiyappam podi': 'ഇടിയപ്പപ്പൊടി',
  'rice flour': 'അരിപ്പൊടി',
  'corn flour': 'കോൺഫ്ലവർ',
  'oats': 'ഓട്സ്',
  'poha': 'അവൽ',
  'aval': 'അവൽ',
  'puffed rice': 'പൊരി',
  'pori': 'പൊരി',

  // --- Pulses & Legumes ---
  'toor dal': 'തുവരപ്പരിപ്പ്',
  'dal': 'പരിപ്പ്',
  'chana dal': 'കടലപ്പരിപ്പ്',
  'urad dal': 'ഉഴുന്ന് പരിപ്പ്',
  'moong dal': 'ചെറുപയർ പരിപ്പ്',
  'green gram': 'ചെറുപയർ',
  'black chana': 'കടല (കറുത്ത കടല)',
  'kabuli chana': 'വെള്ളക്കടല (കാബൂളി)',
  'chickpeas': 'കടല',
  'muthira': 'മുതിര',
  'horse gram': 'മുതിര',
  'horsegram': 'മുതിര',
  'vanpayar': 'വൻപയർ',
  'cowpea': 'വൻപയർ',
  'masoor dal': 'മസൂർ പരിപ്പ്',
  'green peas': 'പച്ചപ്പട്ടാണി / ഗ്രീൻ പീസ്',
  'pattani': 'പട്ടാണി',
  'soya chunks': 'സോയാ ചങ്ക്സ്',

  // --- Spices & Masala ---
  'tamarind': 'വാളൻപുളി',
  'valanpuli': 'വാളൻപുളി',
  'puli': 'വാളൻപുളി',
  'kudampuli': 'കുടമ്പുളി',
  'cambodge': 'കുടമ്പുളി',
  'asafoetida': 'കായം',
  'kayam': 'കായം',
  'hing': 'കായം',
  'turmeric powder': 'മഞ്ഞൾപ്പൊടി',
  'turmeric': 'മഞ്ഞൾ',
  'chilli powder': 'മുളകുപൊടി',
  'kashmiri chilli powder': 'കാശ്മീരി മുളകുപൊടി',
  'coriander powder': 'മല്ലിപ്പൊടി',
  'coriander': 'മല്ലി',
  'cumin seeds': 'ജീരകം',
  'cumin': 'ജീരകം',
  'jeera': 'ജീരകം',
  'fennel seeds': 'പെരുംജീരകം',
  'fennel': 'പെരുംജീരകം',
  'mustard seeds': 'കടുക്',
  'mustard': 'കടുക്',
  'kaduku': 'കടുക്',
  'fenugreek': 'ഉലുവ',
  'uluva': 'ഉലുവ',
  'cardamom': 'ഏലക്കായ്',
  'elakka': 'ഏലക്കായ്',
  'cloves': 'ഗ്രാമ്പൂ',
  'clove': 'ഗ്രാമ്പൂ',
  'grampu': 'ഗ്രാമ്പൂ',
  'cinnamon': 'കറുവപ്പട്ട',
  'karuvapatta': 'കറുവപ്പട്ട',
  'black pepper': 'കുരുമുളക്',
  'pepper': 'കുരുമുളക്',
  'black pepper powder': 'കുരുമുളകുപൊടി',
  'sambar powder': 'സാമ്പാർ പൊടി',
  'rasam powder': 'രസം പൊടി',
  'garam masala': 'ഗരം മസാല',
  'chicken masala': 'ചിക്കൻ മസാല',
  'meat masala': 'മീറ്റ് മസാല',
  'fish masala': 'ഫിഷ് മസാല',
  'biryani masala': 'ബിരിയാണി മസാല',
  'dry ginger': 'ചുക്ക്',
  'chukku': 'ചുക്ക്',
  'ajwain': 'അയമോദകം',
  'ayamodakam': 'അയമോദകം',
  'star anise': 'തക്കോലം',
  'thakolam': 'തക്കോലം',
  'nutmeg': 'ജാതിക്ക',
  'mace': 'ജാതിപത്രി',
  'dry red chilli': 'ഉണക്കമുളക്',
  'dry chilly': 'ഉണക്കമുളക്',

  // --- Oils, Salt & Sugar ---
  'coconut oil': 'വെളിച്ചെണ്ണ',
  'velichenna': 'വെളിച്ചെണ്ണ',
  'sunflower oil': 'സൺഫ്ലവർ ഓയിൽ',
  'gingelly oil': 'നല്ലെണ്ണ (എള്ളെണ്ണ)',
  'sesame oil': 'നല്ലെണ്ണ (എള്ളെണ്ണ)',
  'mustard oil': 'കടുകെണ്ണ',
  'palm oil': 'പാം ഓയിൽ',
  'palmolein': 'പാമോലിൻ ഓയിൽ',
  'rice bran oil': 'റൈസ് ബ്രാൻ ഓയിൽ (തവിട്ടെണ്ണ)',
  'olive oil': 'ഒലിവ് ഓയിൽ',
  'ghee': 'നെയ്യ്',
  'cow ghee': 'പശുവിൻ നെയ്യ്',
  'salt': 'ഉപ്പ്',
  'rock salt': 'കല്ലുപ്പ്',
  'crystal salt': 'കല്ലുപ്പ്',
  'powdered salt': 'പൊടിയുപ്പ്',
  'pink salt': 'ഇന്തുപ്പ് (Pink Salt)',
  'sugar': 'പഞ്ചസാര',
  'brown sugar': 'ബ്രൗൺ ഷുഗർ',
  'jaggery': 'ശർക്കര',
  'jaggery powder': 'ശർക്കരപ്പൊടി',
  'sharkara': 'ശർക്കര',
  'palm jaggery': 'കരിപ്പെട്ടി (പനഞ്ചക്കര)',
  'karippetti': 'കരിപ്പെട്ടി',
  'kalkandam': 'കൽക്കണ്ടം',

  // --- Dairy & Meat ---
  'milk': 'പാൽ',
  'curd': 'തൈര്',
  'butter': 'വെണ്ണ (Butter)',
  'paneer': 'പനീർ (Paneer)',
  'eggs': 'കോഴിമുട്ട',
  'egg': 'മുട്ട',
  'chicken': 'കോഴിയിറച്ചി (ചിക്കൻ)',
  'broiler chicken': 'കോഴിയിറച്ചി (ചിക്കൻ)',
  'mutton': 'ആട്ടിറച്ചി (മട്ടൻ)',
  'beef': 'പോത്തിറച്ചി (ബീഫ്)',
  'mackerel': 'അയല',
  'sardine': 'മത്തി / ചാള',
  'prawns': 'ചെമ്മീൻ',
  'shrimp': 'ചെമ്മീൻ',
  'pomfret': 'ആവോലി',
  'tuna': 'ചൂര',
  'anchovy': 'കൊഴുവാ (നത്തോലി)',

  // --- Bakery, Snacks & Beverages ---
  'banana chips': 'നേന്ത്രക്കായ വറുത്തത് (Banana Chips)',
  'tapioca chips': 'കപ്പ ചിപ്സ് (Tapioca Chips)',
  'sarkaravaratty': 'ശർക്കര വരട്ടി',
  'sharkara varatty': 'ശർക്കര വരട്ടി',
  'ulli vada': 'ഉള്ളിവട',
  'uzhunnu vada': 'ഉഴുന്നുവട',
  'pappadam': 'പപ്പടം',
  'bread': 'ബ്രെഡ്',
  'rusk': 'റസ്ക്',
  'tea': 'ചായപ്പൊടി',
  'tea powder': 'ചായപ്പൊടി',
  'coffee': 'കാപ്പിപ്പൊടി',
  'coffee powder': 'കാപ്പിപ്പൊടി',
  'chukku kappi': 'ചുക്കുകാപ്പി',
  'green tea': 'ഗ്രീൻ ടീ',
  'honey': 'തേൻ',
  'tomato sauce': 'തക്കാളി സോസ് (Tomato Sauce)',
  'tomato ketchup': 'തക്കാളി കെച്ചപ്പ് (Tomato Ketchup)',
  'vermicelli': 'സേമിയ',
  'semiya': 'സേമിയ',
  'noodles': 'നൂഡിൽസ്',
};

// Pre-sorted list of keys by length descending to ensure specific phrases match before single words
const SORTED_KEYS = Object.keys(MALAYALAM_PRODUCT_NAMES).sort((a, b) => b.length - a.length);

const MODIFIER_WORDS = [
  'sauce',
  'ketchup',
  'paste',
  'puree',
  'pickle',
  'chips',
  'squash',
  'truffles',
  'cookies',
  'biscuit',
  'biscuits',
  'powder',
  'masala',
  'oil',
  'syrup',
  'jam',
  'spread',
  'noodles',
];

export function getMalayalamName(name: string): string {
  if (!name) return '';
  const trimmed = name.trim();
  
  // Check if it's already in Malayalam script (Unicode range for Malayalam: 0D00–0D7F)
  if (/[\u0D00-\u0D7F]/.test(trimmed)) {
    return trimmed;
  }

  const lower = trimmed.toLowerCase();

  // 1. Direct exact dictionary match
  if (MALAYALAM_PRODUCT_NAMES[lower]) {
    return MALAYALAM_PRODUCT_NAMES[lower];
  }

  // 2. Clean common grocery catalog prefixes (Veg, Fresh, Country, Pure, etc.)
  const cleanPrefix = lower
    .replace(/^veg\s+/i, '')
    .replace(/^fresh\s+/i, '')
    .replace(/^crisp\s+/i, '')
    .trim();

  if (MALAYALAM_PRODUCT_NAMES[cleanPrefix]) {
    return MALAYALAM_PRODUCT_NAMES[cleanPrefix];
  }

  // 3. Check compound phrases first (e.g. 'tomato sauce' matches before 'tomato')
  for (const key of SORTED_KEYS) {
    if (lower.includes(key)) {
      // Safety check: if key is a raw single produce (like 'tomato' or 'banana')
      // but the product title contains a modifier word (like 'sauce', 'chips', 'pickle', 'powder'),
      // do NOT misclassify it as raw vegetable/fruit unless that modifier is part of the key!
      const isRawSingleProduce = ['tomato', 'banana', 'chilli', 'onion', 'mango', 'orange', 'grape', 'strawberry', 'coconut', 'garlic', 'ginger'].includes(key);
      if (isRawSingleProduce) {
        const hasModifier = MODIFIER_WORDS.some((mod) => lower.includes(mod) && !key.includes(mod));
        if (hasModifier) {
          continue;
        }
      }
      return MALAYALAM_PRODUCT_NAMES[key];
    }
  }

  return trimmed;
}
