import { pool } from '../db/pool';
import fs from 'fs';
import path from 'path';

// Dictionary mapping common English product names/terms to authentic Kerala Malayalam
export const KERALA_MALAYALAM_TRANSLATIONS: Record<string, string> = {
  // === VEGETABLES ===
  'Veg Tomato Bangalore': 'ബാംഗ്ലൂർ തക്കാളി',
  'Veg Tomato Country': 'നാടൻ തക്കാളി',
  'VEG ONION KG': 'സവാള (വലിയ ഉള്ളി)',
  'Veg Sambar Onion': 'ചെറിയ ഉള്ളി (സാമ്പാർ ഉള്ളി)',
  'Veg Potato': 'ഉരുളക്കിഴങ്ങ്',
  'Veg Baby Potato': 'ചെറിയ ഉരുളക്കിഴങ്ങ്',
  'Veg Ladies Finger': 'വെണ്ടയ്ക്ക',
  'Veg Green Chilli': 'പച്ചമുളക്',
  'Veg Drumstick': 'മുരിങ്ങക്കായ',
  'Veg Bitter Gourd Hybrid': 'പാവയ്ക്ക',
  'Veg Bitter Gourd Small': 'നാടൻ പാവയ്ക്ക (കൈപ്പക്ക)',
  'Veg Bottle Gourd': 'ചുരയ്ക്ക',
  'Veg Snake Gourd': 'പടവലങ്ങ',
  'Veg Ash Gourd': 'കുമ്പളങ്ങ',
  'Veg Country Pumpkin': 'നാടൻ മത്തങ്ങ',
  'Veg Ridge Gourd': 'പീച്ചിങ്ങ',
  'Veg Coccinia': 'കോവയ്ക്ക',
  'Veg Colocasia': 'ചേമ്പ്',
  'Veg Yam / Karunaikizhangu': 'ചേന',
  'Veg Tapioca Roots': 'കപ്പ (മരച്ചീനി)',
  'Veg Raw Banana': 'ഏത്തക്കായ (പച്ചക്കായ)',
  'Veg Raw Mango': 'പച്ചമാങ്ങ',
  'Veg Broad Beans': 'അമരക്ക',
  'Veg Cluster Beans': 'കൊത്തമര',
  'Veg Cucumber Country': 'നാടൻ വെള്ളരിക്ക',
  'Veg Cucumber Malabar': 'കണിവെള്ളരി',
  'Veg French Cucumber': 'സാലഡ് വെള്ളരിക്ക',
  'Crisp Green Cucumber': 'വെള്ളരിക്ക',
  'Veg French Beans': 'ബീൻസ്',
  'Veg Butter Beans': 'ബട്ടർ ബീൻസ്',
  'Veg Carrot': 'കാരറ്റ്',
  'Veg Beetroot': 'ബീറ്റ്‌റൂട്ട്',
  'Veg Cabbage': 'കാബേജ്',
  'Veg Chinese Cabbage': 'ചൈനീസ് കാബേജ്',
  'Veg Cauliflower': 'കോളിഫ്ലവർ',
  'Veg Broccoli': 'ബ്രോക്കോളി',
  'Veg Capsicum Green': 'പച്ച ക്യാപ്സിക്കം',
  'Capsicum Red': 'ചുവന്ന ക്യാപ്സിക്കം',
  'Veg Bajji Capsicum': 'ബജ്ജി മുളക്',
  'Bajji Capsicum': 'ബജ്ജി മുളക്',
  'Gundu Chilli Green': 'ഗുണ്ടു മുളക്',
  'Veg Garlic': 'വെളുത്തുള്ളി',
  'Veg Ginger': 'ഇഞ്ചി',
  'Fresh Wayanad Ginger': 'വയനാടൻ ഇഞ്ചി',
  'Veg Ginger Mango': 'മാങ്ങാ ഇഞ്ചി',
  'Mango Ginger': 'മാങ്ങാ ഇഞ്ചി',
  'Veg Lemon': 'ചെറുനാരങ്ങ',
  'Veg Curry Leaves': 'കറിവേപ്പില',
  'Veg Coriander Leaves': 'മല്ലിയില',
  'Coriander Leaf': 'മല്ലിയില',
  'Veg Mint Leaves': 'പുതിനയില',
  'Veg Greens Moringa': 'മുരിങ്ങയില',
  'Veg Greens Palak': 'പാലക് ചീര',
  'Veg Greens Thandu Keerai': 'തണ്ട് ചീര',
  'Veg Greens Siru Keerai': 'ചെറുചീര',
  'Veg Greens Arai Keerai': 'അരക്കീര',
  'Veg Greens Akathi Keerai': 'അഗത്തിച്ചീര',
  'Veg Greens Ponnagkanni Keerai': 'പൊന്നങ്കണ്ണി ചീര',
  'Ponnakanni Keerai': 'പൊന്നങ്കണ്ണി ചീര',
  'Veg Greens Manathakali Keerai': 'മണത്തക്കാളി ഇല',
  'Veg Greens Fenugreek Leaves': 'ഉലുവയില',
  'Veg White Radish': 'മുള്ളങ്കി',
  'Veg Sweet Potato': 'മധുരക്കിഴങ്ങ്',
  'Veg Coconut Small': 'തേങ്ങ',
  'Veg Banana Flower': 'വാഴക്കൂമ്പ് (കുടപ്പൻ)',
  'Veg Banana Stem': 'വാഴപ്പിണ്ടി',
  'Banana Stem': 'വാഴപ്പിണ്ടി',
  'Veg Banana Leaf': 'വാഴയില',
  'Veg Brinjal Ujala': 'നീളൻ വഴുതനങ്ങ',
  'Veg Brinjal Vari': 'വരി വഴുതനങ്ങ',
  'Brinjal Round Suphol': 'ഉരുണ്ട വഴുതനങ്ങ',
  'Veg Knol khol': 'കോൾറാബി (Knol Khol)',
  'Veg Chow Chow': 'ചൗ ചൗ',
  'Veg Celery': 'സെലറി',
  'Veg Lettuce Iceberg': 'ലെറ്റൂസ്',
  'Veg Parsley': 'പാർസിലി',
  'Veg Spring Onion': 'സ്പ്രിംഗ് ഒനിയൻ (ഉള്ളിത്തണ്ട്)',
  'Veg Leeks': 'ലീക്സ്',
  'Zucchini Yellow': 'മഞ്ഞ സൂക്കിനി',
  'Veg Baby Corn': 'ബേബി കോൺ',
  'Veg Baby Corn  200gm': 'ബേബി കോൺ 200g',
  'Baby Corn Peeled': 'ബേബി കോൺ തൊലി കളഞ്ഞത്',
  'Veg American Sweet Corn': 'സ്വീറ്റ് കോൺ (മധുരച്ചോളം)',
  'Veg Corn': 'ചോളം',
  'Veg Mushroom Box': 'കൂൺ (Mushroom)',
  'Mushrooms': 'കൂൺ',
  'Veg Gooseberry Amla': 'നെല്ലിക്ക',
  'Veg Fresh Groundnut': 'പച്ചക്കപ്പലണ്ടി',
  'Cow Pea Karamani / Nadan Payar': 'നാടൻ വൻപയർ (പയർ)',
  'Soya Beans': 'സോയാബീൻ',
  'Pirandai / Veldt Grape': 'ചങ്ങലംപരണ്ട',
  'Turmeric Plant Fresh': 'പച്ചമഞ്ഞൾ',
  'Paraval': 'പടവലം (പോട്‌വൽ)',
  'Parwal': 'പടവലം (പോട്‌വൽ)',
  'Mahali Kizhangu': 'മാഹളി കിഴങ്ങ്',
  'Mahali Potato': 'മാഹളി കിഴങ്ങ്',
  'Mudavattukal Kilangu': 'മുടവത്തു കാൽ കിഴങ്ങ്',
  'Mudavattu Kilangu': 'മുടവത്തു കാൽ കിഴങ്ങ്',

  // === FRUITS ===
  'Banana Nendran / Ethan': 'നേന്ത്രപ്പഴം (ഏത്തപ്പഴം)',
  'Banana Poovan': 'പൂവൻ പഴം',
  'Banana Red': 'ചെങ്കദളി പഴം (ചുവന്ന പഴം)',
  'Banana Yelakki': 'ഞാലിപ്പൂവൻ പഴം',
  'Banana Karpooravalli': 'കർപ്പൂരവള്ളി പഴം',
  'Banana Morris': 'റോബസ്റ്റ പഴം (മോറിസ്)',
  'Banana Rasthali': 'രസകദളി പഴം',
  'Banana Green': 'പച്ചക്കായ',
  'Banana Hill': 'മലവാഴപ്പഴം (കുന്നൻ പഴം)',
  'Guava': 'പേരയ്ക്ക',
  'Guava Imported': 'പേരയ്ക്ക (ഇംപോർട്ടഡ്)',
  'Papaya': 'പപ്പായ (കപ്പങ്ങ / ഓമക്ക)',
  'Black Grapes Paneer': 'പനീർ മുന്തിരി (കറുത്ത മുന്തിരി)',
  'Grapes Red Globe Indian': 'റെഡ് ഗ്ലോബ് മുന്തിരി (ചുവന്ന മുന്തിരി)',
  'Apple Shimla': 'ഷിംല ആപ്പിൾ',
  'Apple Fuji': 'ഫ്യൂജി ആപ്പിൾ',
  'Apple Royal Gala': 'റോയൽ ഗാല ആപ്പിൾ',
  'Apple Red Delicious': 'റെഡ് ഡെലീഷ്യസ് ആപ്പിൾ',
  'Green Apple': 'ഗ്രീൻ ആപ്പിൾ',
  'Mosambi': 'മുസംബി (മധുരനാരങ്ങ)',
  'Musk Melon / Mulampazham': 'ഷമാം (മുഴംപഴം)',
  'Orange Imported': 'ഓറഞ്ച്',
  'Baby Orange': 'ചെറിയ ഓറഞ്ച്',
  'Anjeer Fruit': 'അത്തിപ്പഴം (Anjeer)',
  'Anjeer Fruit Box Small': 'അത്തിപ്പഴം ബോക്സ്',
  'Indian Plums': 'പ്ലംസ് (ഇന്ത്യൻ പ്ലം)',
  'Country Green Pears': 'നാടൻ സബർജില്ലി (Green Pears)',
  'Pear Green Howell': 'സബർജില്ലി (Green Pears)',
  'Red Pears': 'ചുവന്ന സബർജില്ലി (Red Pears)',
  'Kiwi': 'കിവി',
  'Dragon Fruit': 'ഡ്രാഗൺ ഫ്രൂട്ട്',
  'Avocado': 'വെണ്ണപ്പഴം (Avocado)',
  'Strawberry Box': 'സ്ട്രോബെറി ബോക്സ്',
  'Blueberry Box': 'ബ്ലൂബെറി ബോക്സ്',
  'Cherry': 'ചെറി (Cherry)',
  'Durian Imported': 'ഡ്യൂറിയൻ പഴം',
  'Perambam Palam': 'പ്രമ്പം പഴം',

  // === RICE & GRAINS ===
  'Aashirbad Kuruva / Cherumani Rice 1Kg / Loose': 'ആശീർവാദ് കുറുവ / ചെറുമണി അരി 1 kg',
  'Cherumani / Kuruva Rice 5 kg ( SS Kranthi )': 'ചെറുമണി / കുറുവ അരി 5 kg (SS Kranthi)',
  'Golden Jaya Rice 5 kg ( Loose )': 'ഗോൾഡൻ ജയ അരി 5 kg',
  'Idly Ponni rice 1 kg': 'ഇഡ്ഡലി പൊന്നി അരി 1 kg',
  'Ponni Rice 1kg / Baby': 'പൊന്നി അരി 1 kg',
  'India Gate Basmati Rice Golden Sella Supreme 1 Kg / Mandi & Biryani Rice': 'ഇന്ത്യാ ഗേറ്റ് ബാസ്മതി റൈസ് (ഗോൾഡൻ സെല്ല) 1 kg',
  'Indiagate Basmati Rice White Sella Tiber / Biriyani Rice 1kg loose': 'ഇന്ത്യാ ഗേറ്റ് ബാസ്മതി റൈസ് (വൈറ്റ് സെല്ല) 1 kg',
  'Alibaba Basmati Rice 1 Kg (biryani rice)': 'അലിബാബ ബാസ്മതി ബിരിയാണി അരി 1 kg',
  'Barkath silver premium biriyani rice 1 kg (Small rice)': 'ബർക്കത്ത് സിൽവർ ബിരിയാണി അരി (ജീരകശാല) 1 kg',
  'Double Rose Jeeragasala Rice 1 Kg / Biryani & Ghee Rice': 'ഡബിൾ റോസ് ജീരകശാല നെയ്ച്ചോർ അരി 1 kg',
  'Rose Kaima, Biriyani & Ghee Rice 1 kg': 'റോസ് കൈമ ബിരിയാണി അരി 1 kg',
  'Kaveri Unda Matta 10 kg Bag': 'കാവേരി ഉണ്ടമട്ട അരി 10 kg',
  'Kaveri Vadi Matta Rice 5 Kg ( Loose )': 'കാവേരി വടിമട്ട അരി 5 kg',
  'Keerthi Vadi Matta rice 5 kg loose': 'കീർത്തി വടിമട്ട അരി 5 kg',
  'Matta Short Grain Rice 5 kg': 'മട്ട അരി 5 kg',
  'Vadimatta Rice 5 kg': 'വടിമട്ട അരി 5 kg',
  'SS Kranthi Rice 5 Kg Loose': 'എസ് എസ് ക്രാന്തി അരി 5 kg',
  'unakkalari 1 kg (Raw Rice)': 'ഉണക്കലരി 1 kg (പച്ചരി)',
  'Unda Pachari 1 kg ( Raw Rice)': 'ഉണ്ട പച്ചരി 1 kg',
  'Matta AVAL 500g- Pavizham': 'പവിഴം മട്ട അവൽ 500g',
  'Choice Matta Aval 400 Gm': 'ചോയ്സ് മട്ട അവൽ 400g',
  'Choice White Aval 400 Gm': 'ചോയ്സ് വെള്ള അവൽ 400g',
  'Matta Broken Rice 500g ( Podiyari ) Unifolks': 'മട്ട പൊടിയരി 500g',
  'Pavizham Matta Broken Rice, 500g': 'പവിഴം മട്ട പൊടിയരി 500g',
  'Pori / Puffed Rice 50gm Pack': 'പൊരി 50g',
  'Ajmi Fresh Made Double Roasted Upma Rava 1 Kg': 'അജ്മി വറുത്ത ഉപ്പുമാവ് റവ 1 kg',
  'Choice Double Roasted Rava 1 Kg': 'ചോയ്സ് വറുത്ത റവ 1 kg',
  'Choice Fried Rava 500 Gm': 'ചോയ്സ് റവ 500g',
  'Double Horse Roasted Rava 1 kg': 'ഡബിൾ ഹോഴ്സ് വറുത്ത റവ 1 kg',
  'Ponkathir Bency Rava 500g / Special Uppumavu Rava': 'പൊൻകതിർ ബെൻസി റവ 500g',
  'Rava Loose 500gm': 'റവ 500g',
  'Elite Broken Wheat 500g': 'എലൈറ്റ് ഗോതമ്പ് നുറുക്ക് 500g',
  'Elite Samba Broken Wheat 500g': 'എലൈറ്റ് സമ്പാ ഗോതമ്പ് നുറുക്ക് 500g',
  'Shaalimar Broken Wheat 500g / Gothambu Nurukku': 'ശാലിമാർ ഗോതമ്പ് നുറുക്ക് 500g',
  'Fira Jack N Mix Raw Jackfruit Flour 200 g (Jackfruit Flour)': 'പച്ചച്ചക്കപ്പൊടി (ചക്കപ്പൊടി) 200g',
  'Suraj Matta Palada 200g': 'സൂരജ് മട്ട പാലട 200g',
  'Mulaku kondattam 10.rs packet': 'മുളക് കൊണ്ടാട്ടം',
  'Soda Podi Packet': 'സോഡാപ്പൊടി പാക്കറ്റ്',

  // === PULSES & LEGUMES ===
  '1st Thuvaraparippu / Toor Dal 500gm': 'തുവരപ്പരിപ്പ് 500g',
  'Thuvaraparippu - Toor Dal 500gm': 'തുവരപ്പരിപ്പ് 500g',
  'Cherupayar 500g / Green Gram': 'ചെറുപയർ 500g',
  'Cherupayar Parippu 250gm': 'ചെറുപയർ പരിപ്പ് 250g',
  'Dry Green Peas 500g': 'ഉണക്കപ്പട്ടാണി (പച്ചപ്പട്ടാണി) 500g',
  'Kadala  500 gm': 'കടല 500g',
  'Kadala Big 500gm ( Bengal )': 'വലിയ കടല (ബംഗാൾ കടല) 500g',
  'Kadalaparippu 250g -Channa Dal)': 'കടലപ്പരിപ്പ് 250g',
  'Masoor Dal 500gm \\ Red parippu': 'മസൂർ പരിപ്പ് (ചുവന്ന പരിപ്പ്) 500g',
  'Muthira -Horsegram) 500 gm': 'മുതിര 500g',
  'Roasted Gram Dal -Pottu Kadala) 250gm': 'പൊട്ടുകടല 250g',
  'Soya Chunks Big 250gm / Loose': 'സോയാ ചങ്ക്സ് വലിയത് 250g',
  'Soya Chunks Small 250gm': 'സോയാ ചങ്ക്സ് ചെറിയത് 250g',
  'Vada Parippu / Piece Parippu 500gm': 'വടപ്പരിപ്പ് 500g',
  'Vanpayar -Flat 500 Gm': 'വൻപയർ 500g',
  'White Kadala- Kabhoolikadala 500gm': 'വെള്ളക്കടല (കാബൂളി കടല) 500g',
  'White Peas / Matar 500g': 'വെള്ളപ്പട്ടാണി 500g',

  // === SPICES ===
  'AB Tamarind  250g Seedless (Puli)': 'വാളൻപുളി (കുരുയില്ലാത്തത്) 250g',
  'AB Tamarind / Valanpuli 500 g': 'വാളൻപുളി 500g',
  'AB Tamarind / Valanpuli Seedless 500 g': 'വാളൻപുളി (കുരുയില്ലാത്തത്) 500g',
  'Tholur Tamarind 250g ( Puli )': 'തോലൂർ വാളൻപുളി 250g',
  'Tamarind  250g  (Puli) AB Products': 'വാളൻപുളി 250g',
  'Black Cumin Seed -Karimjeerakam': 'കരിഞ്ചീരകം',
  'Black Pepper 100g': 'കുരുമുളക് 100g',
  'Cardamom / Elakkaya / 20 Rs/- pack': 'ഏലക്കായ് പാക്കറ്റ്',
  'Cardamom / Elakkaya 50g': 'ഏലക്കായ് 50g',
  'Clove / Grampu 10rs/- pack': 'ഗ്രാമ്പൂ പാക്കറ്റ്',
  'Clove / Grampu 50g': 'ഗ്രാമ്പൂ 50g',
  'Cinnamon Stick  / Karuvapatta 50g': 'കറുവപ്പട്ട 50g',
  'Cinnamon Stick  / Karuvapatta Rs 10 pack': 'കറുവപ്പട്ട പാക്കറ്റ്',
  'Cumin Seeds 100g ( Jeerakam ) Eastern': 'ജീരകം 100g (ഈസ്റ്റേൺ)',
  'Cumin Seeds 50g / Jeerakam / Essan': 'ജീരകം 50g',
  'Essen Cumin Seeds / Jeerakam 100g': 'ജീരകം 100g',
  'Double Horse Coriander Powder 250 g': 'ഡബിൾ ഹോഴ്സ് മല്ലിപ്പൊടി 250g',
  'Double Horse Powder - Chilly 250 g': 'ഡബിൾ ഹോഴ്സ് മുളകുപൊടി 250g',
  'Double Horse Puttupodi - White 1 kg': 'ഡബിൾ ഹോഴ്സ് വെള്ള പുട്ടുപൊടി 1 kg',
  'Eastern Fennel Seeds 100g / Perumjeerakam': 'പെരുംജീരകം 100g (ഈസ്റ്റേൺ)',
  'Fennel Seeds 100g / Perum Jeerakam / Essen': 'പെരുംജീരകം 100g',
  'Eastern Fenugreek ( Whole ) 100g / Uluva': 'ഉലുവ 100g (ഈസ്റ്റേൺ)',
  'Essen Fenugreek / Uluva 100 g': 'ഉലുവ 100g',
  'Fenugreek 250g ( Uluva ) Kitchen Treasures': 'ഉലുവ 250g (കിച്ചൺ ട്രഷേർസ്)',
  'Essen Kaduku / Mustard 250g': 'കടുക് 250g',
  'Mustard 100g (Kaduk ) Kitchen Treasures': 'കടുക് 100g',
  'Mustard 100gm  (kaduk) Eastern': 'കടുക് 100g (ഈസ്റ്റേൺ)',
  'Swamis Mustard seeds 100 Gm (Kaduk)': 'സ്വാമീസ് കടുക് 100g',
  'Malli- Coriander 250gm': 'മല്ലി 250g',
  'Whole Coriander / Malli 100 Gm': 'മുഴുൻ മല്ലി 100g',
  'Manjal / DryTurmeric 250gm': 'ഉണക്കമഞ്ഞൾ 250g',
  'Kudampuli 100gm': 'കുടമ്പുളി 100g',
  'Kudampuli / Cambodge 60g Packet': 'കുടമ്പുളി 60g',
  'Tholur Kudampuli 100g Cambodge': 'തോലൂർ കുടമ്പുളി 100g',
  'L.G Stone Kayam / Asafoetida 100 Gm': 'എൽ.ജി കട്ടക്കായം 100g',
  'L G Asafoetida Powder 100 g (Kayam podi)': 'എൽ.ജി കായപ്പൊടി 100g',
  'LG Kayam Podi 15g \\ Asafoetida Powder': 'എൽ.ജി കായപ്പൊടി 15g',
  'Perum Kayam 7g / Compounded Asafoetida Cake': 'പെരുങ്കായം 7g',
  'Viswabrahmas Asafoetida Cake 100 g': 'വിശ്വബ്രാഹ്മ കട്ടക്കായം 100g',
  'Viswabrahmas Asafoetida Powder 100 g': 'വിശ്വബ്രാഹ്മ കായപ്പൊടി 100g',
  'Viswabrahmas Asafoetida Powder 50 g': 'വിശ്വബ്രാഹ്മ കായപ്പൊടി 50g',
  'Whole Garam Masala Rs;10 Packet': 'മുഴുൻ ഗരം മസാല പാക്കറ്റ്',
  'Tandoori Masala 50g / City\'s Master Chef': 'തന്തൂരി മസാല 50g',
  'Fira Arrowroot Powder 200 g': 'കൂവപ്പൊടി (Arrowroot Powder) 200g',
  'Happilo Black Raisins - Premium Afghani Seedless 250 g': 'കറുത്ത ഉണക്കമുന്തിരി (അഫ്ഗാനി) 250g',
  'Happilo Premium Omani Dates - International 250 g': 'ഒമാനി ഈത്തപ്പഴം 250g',

  // === STAPLES ===
  'Aashirvaad 100% Whole Wheat Atta': 'ആശീർവാദ് 100% ഗോതമ്പ് ആട്ട',
  'Ayamodakam / Ajwain Seeds 50g': 'അയമോദകം 50g',
  'Bakers Baking Soda 100g': 'ബേക്കിംഗ് സോഡ 100g',
  'Bakers Oregano 35g': 'ഒറിഗാനോ 35g',
  'Bay Leaves 10g': 'വഴനയില (Bay Leaves) 10g',
  'Bellam (Sharkara) 500g': 'ശർക്കര ഉണ്ട 500g',
  'Biriyani Mix- Kit 1 Kg': 'ബിരിയാണി മിക്സ് കിറ്റ് 1 kg',
  'Brooke Bond 3 Roses 250g': '3 റോസസ് ചായപ്പൊടി 250g',
  'Bush Biriyani Essence 20ml': 'ബിരിയാണി എസ്സെൻസ് 20ml',
  'Bush Pineapple Essence 28ml': 'പൈനാപ്പിൾ എസ്സെൻസ് 28ml',
  'Bush Vanilla Essence 28ml': 'വാനില എസ്സെൻസ് 28ml',
  'Dry Chilly With Stem / Unakka mulagu 100gm': 'ഞെട്ടുള്ള ഉണക്കമുളക് 100g',
  'Dry Ginger / Chukku 20 Rupees Packet': 'ചുക്ക് പാക്കറ്റ്',
  'Dry Yeast': 'യീസ്റ്റ് (Dry Yeast)',
  'Eastern Chukku Kappi 100gm': 'ഈസ്റ്റേൺ ചുക്കുകാപ്പി 100g',
  'Eastern Ginger Garlic Paste 30g': 'ഈസ്റ്റേൺ ഇഞ്ചി വെളുത്തുള്ളി പേസ്റ്റ് 30g',
  'Elite Half Cooked Chapati 10 Pieces / 450g': 'എലൈറ്റ് റെഡിമെയ്ഡ് ചപ്പാത്തി (10 എണ്ണം) 450g',
  'Elite Half Cooked Malabar Parotta, 9 + 2 ( 2 Parottas Free )': 'എലൈറ്റ് മലബാർ പൊറോട്ട (9 + 2 സൗജന്യം)',
  'Ellu Black 20g / packet': 'കറുത്ത എള്ള് 20g',
  'Ellu / Black Sesame Seeds Loose 100g ( ellu)': 'കറുത്ത എള്ള് 100g',
  'Ellu / Black Sesame Seeds Loose 250g': 'കറുത്ത എള്ള് 250g',
  'Fruitoman\'s Baking Powder 50 gm': 'ഫ്രൂട്ടോമാൻസ് ബേക്കിംഗ് പൗഡർ 50g',
  'Ginger Garlic Paste 100g Kitchen Treasures': 'ഇഞ്ചി വെളുത്തുള്ളി പേസ്റ്റ് 100g',
  'Idli & Dosa Batter 1 Kg - Thiruvonam': 'തിരുവോണം ഇഡ്ഡലി ദോശ മാവ് 1 kg',
  'Janatha Pappadam 250g Loose': 'ജനത പപ്പടം 250g',
  'Pappadam 100 Gm Loose': 'പപ്പടം 100g',
  'Karingali Dahashamani 40g / Kalan Drugs & Remedies': 'കരിങ്ങാലി ദാഹശമനി 40g',
  'Kashmiri Dry Chilly 250gm': 'കാശ്മീരി ഉണക്കമുളക് 250g',
  'KasKas / Poppy seeds / Black': 'കറുത്ത കസ്കസ് (Poppy Seeds)',
  'KLF Coconad Coconut Milk Powder 100g': 'കെ.എൽ.എഫ് തേങ്ങാപ്പാൽ പൊടി 100g',
  'Natural Groundnut / Peanut / Pacha Kappalandi  250g': 'പച്ചക്കപ്പലണ്ടി 250g',
  'Roasted Peanuts/ Groundnut / Manal Kappalandi 250g': 'മണൽ കപ്പലണ്ടി (വറുത്ത കപ്പലണ്ടി) 250g',
  'Payasakoottu pouch rs.20': 'പായസക്കൂട്ട് പാക്കറ്റ് ₹20',
  'Payasakoottu pouch rs.30': 'പായസക്കൂട്ട് പാക്കറ്റ് ₹30',
  'Plain China Grass 10g / City\'s Master Chef': 'ചൈനാഗ്രാസ് 10g',
  'Prameha Samhari Dahasamani': 'പ്രമേഹ സംഹാരി ദാഹശമനി',
  'Ragi / Pullu 1 Kg': 'റാഗി (കൂവരക് / പുല്ല്) 1 kg',
  'Rasakoot': 'രസക്കൂട്ട്',
  'Saffola Plain Oats 1kg with Free Saffola Oats 300 gm': 'സഫോള പ്ലെയിൻ ഓട്സ് 1 kg (+ 300g സൗജന്യം)',
  'Silver Cafe Chukku Kaapi 30g': 'സിൽവർ കഫേ ചുക്കുകാപ്പി 30g',
  'Thakolam 8g -Star Anise Whole': 'തക്കോലം (Star Anise) 8g',
  'Tholur chukku Kappi Jar Buy 1 Get 1 Free (150g x 2)': 'തോലൂർ ചുക്കുകാപ്പി ജാർ (1 + 1 സൗജന്യം)',
  'Uzhunnu ball 500gm': 'ഉണ്ട ഉഴുന്ന് 500g',

  // === OILS & SUGAR ===
  'Fira Kerala Coconut Oil (Pouch) 1 l': 'ഫിറ കേരള വെളിച്ചെണ്ണ 1 L',
  'Kalpasree Coconut Oil 1 Ltr velichenna': 'കൽപശ്രീ വെളിച്ചെണ്ണ 1 L',
  'KLF Coconad Coconut Oil 900ml. Bottle': 'കെ.എൽ.എഫ് കൊക്കോനാട് വെളിച്ചെണ്ണ 900ml',
  'Parachute 100% Pure Coconut Oil 100 ml': 'പാരഷൂട്ട് ശുദ്ധമായ വെളിച്ചെണ്ണ 100ml',
  'Fortune Kachi Ghani Pure Mustard Oil 500 ml (kadukenna)': 'ഫോർച്യൂൺ കടുകെണ്ണ 500ml',
  'Pavithram Sesame Oil (Nallenna) 1 L': 'പവിത്രം നല്ലെണ്ണ (എള്ളെണ്ണ) 1 L',
  'Sunrich Refined Sunflower Oil 455g': 'സൺറിച്ച് സൺഫ്ലവർ ഓയിൽ 455g',
  'Ruchi Gold Refined Palmolein Oil 425g': 'രുചി ഗോൾഡ് പാമോലിൻ ഓയിൽ 425g',
  'Rice Drops Rice Bran Oil - 1L (pouch) Thavidenna': 'റൈസ് ബ്രാൻ ഓയിൽ (തവിട്ടെണ്ണ) 1 L',
  'Figaro Olive Oil 100 ml': 'ഫിഗാറോ ഒലിവ് ഓയിൽ 100ml',
  'Indulekha Svetakutaja Oil  100 ml': 'ഇന്ദുലേഖ ശ്വേതകുടാജ എണ്ണ 100ml',
  'Maharishi Cow Ghee 500 ml (Cow Ghee)': 'മഹർഷി പശുവിൻ നെയ്യ് 500ml',
  'Milky Mist Ghee 500 ml': 'മിൽക്കി മിസ്റ്റ് നെയ്യ് 500ml',
  'Milma Ghee 100 ml': 'മിൽമ നെയ്യ് 100ml',
  'Double Horse Jaggery Powder 400 g': 'ഡബിൾ ഹോഴ്സ് ശർക്കരപ്പൊടി 400g',
  'Maharishi Ayurveda Jaggery Powder 500 g': 'മഹർഷി ആയുർവേദ ശർക്കരപ്പൊടി 500g',
  'Jyothi Karippetti (palm jaggery) 400gm': 'ജ്യോതി കരിപ്പെട്ടി (പനഞ്ചക്കര) 400g',
  'Kalkandam Ball 10 Rs packet': 'കൽക്കണ്ടം ഉണ്ട പാക്കറ്റ്',
  'Kalkandam Crystal 10 rs packet': 'കൽക്കണ്ടം ക്രിസ്റ്റൽ പാക്കറ്റ്',
  'Panam Kalkandam -10 rs/- pack': 'പനം കൽക്കണ്ടം പാക്കറ്റ്',
  'Keya Everyday Pink Salt 1 kg ( Pink Salt)': 'കേയ ഇന്തുപ്പ് (Pink Salt) 1 kg',
  'Maharishi Ayurveda Himalayan Pink Salt 500 g': 'ഹിമാലയൻ ഇന്തുപ്പ് (Pink Salt) 500g',
  'Pusht Organic Pink Salt Crystal 1 kg': 'ഇന്തുപ്പ് ക്രിസ്റ്റൽ (Pink Salt) 1 kg',
  'Pusht Organic Pink Salt Powder 1 kg': 'ഇന്തുപ്പ് പൊടി (Pink Salt) 1 kg',
  'Pusht Organic Brown Sugar 500 g': 'ബ്രൗൺ ഷുഗർ (തവിട്ടു പഞ്ചസാര) 500g',

  // === DAIRY ===
  'Amul Salted Table Butter': 'അമുൽ ബട്ടർ (വെണ്ണ)',
  'Farm Fresh White Eggs (മുട്ട)': 'ഫ്രഷ് കോഴിമുട്ട (White Eggs)',
  'Fresh Malai Cottage Cheese (Paneer)': 'ഫ്രഷ് മലായ് പനീർ (Paneer)',
  'Milky Mist Sweetened Condensed Milk 395 g': 'മിൽക്കി മിസ്റ്റ് മിൽക്ക് മെയ്ഡ് (കണ്ടൻസ്ഡ് മിൽക്ക്) 395g',
  'Amul Mango Lassi 1 l': 'അമുൽ മാംഗോ ലസ്സി 1 L',
  'Milky Mist Greek Yogurt Natural 100 g': 'മിൽക്കി മിസ്റ്റ് തൈര് (നാച്ചുറൽ യോഗർട്ട്) 100g',
  'Milky Mist Fruit Yoghurt - Mango 100 ml': 'മിൽക്കി മിസ്റ്റ് മാംഗോ യോഗർട്ട് 100ml',
  'Milky Mist Fruit Yoghurt - Blueberry 100 g': 'മിൽക്കി മിസ്റ്റ് ബ്ലൂബെറി യോഗർട്ട് 100g',
  'Milky Mist Fruit Yoghurt - Peach 100 g': 'മിൽക്കി മിസ്റ്റ് പീച്ച് യോഗർട്ട് 100g',
  'Milky Mist Stirred Fruit Yogurt - Strawberry 100 g': 'മിൽക്കി മിസ്റ്റ് സ്ട്രോബെറി യോഗർട്ട് 100g',
  'Skei Tender Coconut Ice Cream Tub': 'സ്കീ ഇളനീർ ഐസ്ക്രീം ടബ്',
  'Skei Alphonso Mango Ice Cream Tub': 'സ്കീ അൽഫോൻസോ മാമ്പഴ ഐസ്ക്രീം ടബ്',

  // === MEATS & FISH ===
  'Fresh Broiler Chicken (ചിക്കൻ / കോഴിയിറച്ചി)': 'ഫ്രഷ് കോഴിയിറച്ചി (ചിക്കൻ)',
  'Fresh Goat Mutton Curry Cut (ആട്ടിറച്ചി)': 'ഫ്രഷ് ആട്ടിറച്ചി (മട്ടൻ)',
  'Fresh Tender Beef (പോത്തിറച്ചി / ബീഫ്)': 'ഫ്രഷ് പോത്തിറച്ചി (ബീഫ്)',
  'Fresh Indian Mackerel / Ayala (അയല)': 'ഫ്രഷ് അയല (Mackerel)',
  'Fresh Sardine / Mathi (മത്തി / ചാള)': 'ഫ്രഷ് മത്തി / ചാള (Sardine)',
  'Fresh Tiger Prawns Cleaned (ചെമ്മീൻ)': 'ഫ്രഷ് ചെമ്മീൻ (Prawns)',

  // === SAUCES & CONDIMENTS ===
  'Ambadi Coconut Water Vinegar 350 ml': 'അമ്പാടി തേങ്ങാവെള്ള വിനാഗിരി 350ml',
  'Pavizham Synthetic Vinegar 1 Ltr.': 'പവിഴം വിനാഗിരി 1 L',
  'Anu\'s Tomato Sauce 1 kg': 'അനൂസ് തക്കാളി സോസ് 1 kg',
  'Deepam Tomato Sauce 200 g': 'ദീപം തക്കാളി സോസ് 200g',
  'Dels Tomato Sauce 200 g': 'ഡെൽസ് തക്കാളി സോസ് 200g',
  'Deepam Green Chilli Sauce 200g': 'ദീപം പച്ചമുളക് സോസ് (Green Chilli Sauce) 200g',
  'Anu\'s soya Sauce 200 g': 'അനൂസ് സോയാ സോസ് 200g',
  'Kerala Honey 100 g': 'കേരള ശുദ്ധമായ തേൻ 100g',
  'Grandmas Pineapple & Strawberry Jam Combo 400 g': 'ഗ്രാൻഡ്മാസ് പൈനാപ്പിൾ സ്ട്രോബെറി ജാം 400g',
  'Lion Mixed Fruit Jam Combo Pack 250 g': 'ലയൺ മിക്സഡ് ഫ്രൂട്ട് ജാം 250g',
  'Bambino Roasted Vermicelli 200 g (semiya)': 'ബാംബിനോ വറുത്ത സേമിയ 200g',
  'Bambino Vermicelli 150gm (semiya)': 'ബാംബിനോ സേമിയ 150g',
  'Supriyam Roasted Vermicelli Noodles 170g ( upma semiya)': 'സുപ്രിയം വറുത്ത സേമിയ 170g',
  'Bambino Pasta Macaroni 200 g': 'ബാംബിനോ മാക്രോണി പാസ്ത 200g',
  'Savorit Pasta Macaroni 250g': 'സാവോരിറ്റ് മാക്രോണി പാസ്ത 250g',
  'Fruitoman\'s Veg Noodles 500g': 'ഫ്രൂട്ടോമാൻസ് വെജ് നൂഡിൽസ് 500g',

  // === BEVERAGES ===
  'AVT Premium Tea 1 kg': 'എ.വി.ടി പ്രീമിയം ചായപ്പൊടി 1 kg',
  'Brooke Bond 3 Roses 100g Tea': '3 റോസസ് ചായപ്പൊടി 100g',
  'Brooke Bond Red Label Tea 250gm': 'റെഡ് ലേബൽ ചായപ്പൊടി 250g',
  'Brooke Bond Red Label Natural Care Tea 100 g': 'റെഡ് ലേബൽ നാച്ചുറൽ കെയർ ചായപ്പൊടി 100g',
  'Brooke Bond Taj Mahal Tea 250g': 'താജ് മഹൽ ചായപ്പൊടി 250g',
  'Taj Mahal Tea 500 g': 'താജ് മഹൽ ചായപ്പൊടി 500g',
  'Red Label Dust Tea - Strong 500 g': 'റെഡ് ലേബൽ ഡസ്റ്റ് ചായപ്പൊടി 500g',
  'Red Label Tea - Natural Care 500 g': 'റെഡ് ലേബൽ ചായപ്പൊടി 500g',
  '3 Roses Dust Tea 500 g': '3 റോസസ് ഡസ്റ്റ് ചായപ്പൊടി 500g',
  'Society Masala Tea 500 g (TEA)': 'സൊസൈറ്റി മസാല ചായപ്പൊടി 500g',
  'Society Masala Flavour Tea 250 g': 'സൊസൈറ്റി മസാല ചായപ്പൊടി 250g',
  'Bru Instant Coffee 100 g': 'ബ്രൂ ഇൻസ്റ്റന്റ് കാപ്പിപ്പൊടി 100g',
  'Bru Filter Coffee - Green Label 500 g': 'ബ്രൂ ഫിൽറ്റർ കോഫി 500g',
  'Bru Instant Ground Coffee': 'ബ്രൂ ഇൻസ്റ്റന്റ് കാപ്പിപ്പൊടി',
  'Nescafe Classic Coffee Powder Jar 24gm': 'നെസ്കഫെ ക്ലാസിക് കാപ്പിപ്പൊടി 24g',
  'Silver Cafe Coffee Powder - 100g': 'സിൽവർ കഫേ കാപ്പിപ്പൊടി 100g',
  'Tholur Chukku Kappi 150 g': 'തോലൂർ ചുക്കുകാപ്പി 150g',
  'Lipton Green Tea - Honey, Lemon 100 g': 'ലിപ്റ്റൺ ഗ്രീൻ ടീ (തേൻ & നാരങ്ങ) 100g',
  'Lipton Green Tea Bags - Honey Lemon 25 pcs': 'ലിപ്റ്റൺ ഗ്രീൻ ടീ ബാഗ്സ് (25 എണ്ണം)',
  'Lipton Green Tea - Tulsi Natura 25 pcs': 'ലിപ്റ്റൺ തുളസി ഗ്രീൻ ടീ (25 എണ്ണം)',
  'Grandma\'s Grape Squash 500ml': 'ഗ്രാൻഡ്മാസ് ഗ്രേപ്പ് സ്ക്വാഷ് 500ml',
  'Grandma\'s Mango Squash 700ml': 'ഗ്രാൻഡ്മാസ് മാംഗോ സ്ക്വാഷ് 700ml',
  'Grandma\'s Orange Squash 700ml': 'ഗ്രാൻഡ്മാസ് ഓറഞ്ച് സ്ക്വാഷ് 700ml',
  'Grandma\'s Pineapple Squash 700ml': 'ഗ്രാൻഡ്മാസ് പൈനാപ്പിൾ സ്ക്വാഷ് 700ml',
  'Tang Lemon Instant Mix 500g': 'ടാങ് ലെമൺ ഇൻസ്റ്റന്റ് മിക്സ് (നാരങ്ങ വെള്ളം) 500g',
  'Tang Lemon Instant Mix 75g': 'ടാങ് ലെമൺ ഇൻസ്റ്റന്റ് മിക്സ് 75g',
  'Tang Mango Instant Mix 500g': 'ടാങ് മാംഗോ ഇൻസ്റ്റന്റ് മിക്സ് 500g',
  'Tang Mango Instant Mix 75g': 'ടാങ് മാംഗോ ഇൻസ്റ്റന്റ് മിക്സ് 75g',
  'Tang Orange Instant Mix 500g': 'ടാങ് ഓറഞ്ച് ഇൻസ്റ്റന്റ് മിക്സ് 500g',
  'Tang Orange Instant Mix 75g': 'ടാങ് ഓറഞ്ച് ഇൻസ്റ്റന്റ് മിക്സ് 75g',

  // === BAKERY & SNACKS TRADITIONAL ===
  'Asians Banana Chips 300g': 'ഏഷ്യൻസ് നേന്ത്രക്കായ വറുത്തത് (Banana Chips) 300g',
  'Banana Chips - Round 1 kg': 'നേന്ത്രക്കായ വറുത്തത് (Banana Chips) 1 kg',
  'Sweet karam Nendran Banana Chips': 'നേന്ത്രക്കായ വറുത്തത് (Banana Chips)',
  'Sweet Karam Spicy Nendran  Banana Chips': 'എരിവുള്ള നേന്ത്രക്കായ വറുത്തത് (Spicy Banana Chips)',
  'Sweet karam Kerala Tapioca Chips': 'കേരള കപ്പ ചിപ്സ് (Tapioca Chips)',
  'Sweet Karam Tapioca Chips': 'കപ്പ ചിപ്സ് (Tapioca Chips)',
  'VS Mani & Co Chilli Banana Chips': 'വി എസ് മണി എരിവുള്ള ബനാന ചിപ്സ്',
  'VS Mani & Co Salted Banana Chips': 'വി എസ് മണി ഉപ്പിട്ട ബനാന ചിപ്സ്',
  'VS Mani & Co Pepper Murukku': 'വി എസ് മണി കുരുമുളക് മുറുക്ക്',
  'VS Mani & Co Ribbon Murukku': 'വി എസ് മണി റിബ്ബൺ മുറുക്ക്',
  'Townbus Ribbon Pakkoda': 'ടൗൺബസ് റിബ്ബൺ പക്കോഡ',
  'Townbus Madras Mixture': 'ടൗൺബസ് മദ്രാസ് മിക്സ്ചർ',
  'Thirumala Mysore Pak': 'തിരുമല മൈസൂർ പാക്ക് (Mysore Pak)',
  'Sri Dairy Milk Halwa': 'മിൽക്ക് ഹൽവ (Milk Halwa)',
  'Anandhi Sweet Mixture': 'ആനന്ദി സ്വീറ്റ് മിക്സ്ചർ',
  'Haldiram\'s Panchratan Mixture': 'ഹൽദിറാംസ് പഞ്ചരത്ന മിക്സ്ചർ',
  'Ulli Vada 1 Pcs': 'ഉള്ളിവട (1 എണ്ണം)',
  'Uzhunnu Vada 1 Pcs': 'ഉഴുന്നുവട (1 എണ്ണം)',
  'Tasty Nibbles  Kerala Instant Sadya Palada Payasam Mix  200 g': 'ടേസ്റ്റി നിബിൾസ് സദ്യ പാലട പായസം മിക്സ് 200g',
  'Elite Family Wonder Bread 600g': 'എലൈറ്റ് ബ്രെഡ് 600g',
  'Modern Brown Bread 400gm': 'മോഡേൺ ബ്രൗൺ ബ്രെഡ് 400g',
  'Modern Multigrain Bread 400gm': 'മോഡേൺ മൾട്ടിഗ്രെയിൻ ബ്രെഡ് 400g',
  'Modern Whole Wheat Bread 400gm': 'മോഡേൺ വീറ്റ് ബ്രെഡ് 400g',
  'Aasshirvaad Chapati 450g': 'ആശീർവാദ് ചപ്പാത്തി 450g',
  'Aditi Banana Pudding Cake 150gm': 'അതിഥി ബനാന പുഡ്ഡിംഗ് കേക്ക് 150g',
  'Aditi Carrot Pudding Cake 150gm': 'അതിഥി കാരറ്റ് പുഡ്ഡിംഗ് കേക്ക് 150g',
  'Aditi Dates Pudding Cake 150gm': 'അതിഥി ഈത്തപ്പഴം പുഡ്ഡിംഗ് കേക്ക് 150g',
  'Aditi Jackfruit Pudding Cake 140gm': 'അതിഥി ചക്ക പുഡ്ഡിംഗ് കേക്ക് 140g',
  'Aditi Red Velvet Pudding Cake 150gm': 'അതിഥി റെഡ് വെൽവെറ്റ് കേക്ക് 150g',
  'Black forest Cake Circle Shape 1 Kg': 'ബ്ലാക്ക് ഫോറസ്റ്റ് കേക്ക് (റൗണ്ട്) 1 kg',
  'Black forest Cake Square Shape 1 Kg': 'ബ്ലാക്ക് ഫോറസ്റ്റ് കേക്ക് (സ്ക്വയർ) 1 kg',
  'Red Velvet  Cake Circle Shape 1 Kg': 'റെഡ് വെൽവെറ്റ് കേക്ക് 1 kg',
  'Red Velvet Cake Heart Shape 1 Kg': 'റെഡ് വെൽവെറ്റ് ഹാർട്ട് കേക്ക് 1 kg',
  'Red Velvet Cake Square Shape 1 Kg': 'റെഡ് വെൽവെറ്റ് കേക്ക് 1 kg',
  'Elite Carrot Pudding Cake 500 gm': 'എലൈറ്റ് കാരറ്റ് പുഡ്ഡിംഗ് കേക്ക് 500g',
  'Elite Carrot Pudding  Cake Slices 150g': 'എലൈറ്റ് കാരറ്റ് പുഡ്ഡിംഗ് കേക്ക് 150g',
  'Elite Dates pudding Cake 500g': 'എലൈറ്റ് ഈത്തപ്പഴം പുഡ്ഡിംഗ് കേക്ക് 500g',
  'Elite Jackfruits Pudding Cake 500g': 'എലൈറ്റ് ചക്ക പുഡ്ഡിംഗ് കേക്ക് 500g',
  'Elite Pineapple Pudding Cake 500g': 'എലൈറ്റ് പൈനാപ്പിൾ പുഡ്ഡിംഗ് കേക്ക് 500g',
  'Elite Premium Plum Surprise Cake 330g': 'എലൈറ്റ് പ്ലം കേക്ക് 330g',
  'Elite Premium Plum Surprise Cake 680g': 'എലൈറ്റ് പ്ലം കേക്ക് 680g',
  'Enthralling Choco Black Forest Cake 1 Kg': 'ചോക്കോ ബ്ലാക്ക് ഫോറസ്റ്റ് കേക്ക് 1 kg',
  'Enthralling Choco  Black Forest Cake Premium 1 Kg': 'പ്രീമിയം ചോക്കോ ബ്ലാക്ക് ഫോറസ്റ്റ് കേക്ക് 1 kg',
  'Lovely Heart Black Forest Cake 1 Kg': 'ഹാർട്ട് ബ്ലാക്ക് ഫോറസ്റ്റ് കേക്ക് 1 kg',
  'Skei Chocolate Ice Cream Tub': 'ചോക്ലേറ്റ് ഐസ്ക്രീം ടബ്',
  'Skei Pista Ice Cream Tub': 'പിസ്ത ഐസ്ക്രീം ടബ്',
  'Skei Vanilla Ice Cream Tub': 'വാനില ഐസ്ക്രീം ടബ്',
  'Skei Nut ButterScotch': 'ബട്ടർസ്കോച്ച് ഐസ്ക്രീം ടബ്',
  'Skei Cookies & Cream': 'കുക്കീസ് & ക്രീം ഐസ്ക്രീം',
  'Nescafe Classic Coffee Powder Jar 24gm': 'നെസ്കഫെ ക്ലാസിക് കാപ്പിപ്പൊടി 24g',
  'Bru Instant Coffee - Super Strong 500 g': 'ബ്രൂ ഇൻസ്റ്റന്റ് കാപ്പിപ്പൊടി (സൂപ്പർ സ്ട്രോങ്ങ്) 500g',
  'Bru Cold Coffee 180ml': 'ബ്രൂ കോൾഡ് കോഫി 180ml',
  'Boost Milk shake 180ml': 'ബൂസ്റ്റ് മിൽക്ക് ഷേക്ക് 180ml',
  'Boost Nutrition Drink Pouch 750 g': 'ബൂസ്റ്റ് ഹെൽത്ത് ഡ്രിങ്ക് 750g',
  'Horlicks Health & Nutrition Drink - Chocolate Flavour 500 g': 'ഹോർലിക്സ് ചോക്ലേറ്റ് 500g',
  'Horlicks Health & Nutrition Drink - Classic Malt (Pouch) 750 g': 'ഹോർലിക്സ് ക്ലാസിക് മാൾട്ട് 750g',
  'Aachi Badam Drink Mix 200 g': 'ആച്ചി ബദാം ഡ്രിങ്ക് മിക്സ് 200g',
  'Aqufina Watar 1ltr': 'അക്വാഫിന കുടിവെള്ളം 1 L',
  'Meriba Water 1 ltr (12 pcs)': 'മെരിബ കുടിവെള്ളം 1 L',
  'Meriba Water 2 ltr (6 pcs)': 'മെരിബ കുടിവെള്ളം 2 L',
  'Real Alphonso Mango Nectar Juice 1 no': 'റിയൽ അൽഫോൻസോ മാമ്പഴ ജ്യൂസ് 1 L',
  'Real Fruit Juice -Pink Guava 1 l': 'റിയൽ പേരയ്ക്ക ജ്യൂസ് 1 L',
  'Real Fruit Power - Mango (Aam) Juice 1 L': 'റിയൽ മാമ്പഴ ജ്യൂസ് 1 L',
  'Real Fruit Power - Pomegranate (Anar) 1 L': 'റിയൽ മാതളനാരങ്ങ ജ്യൂസ് 1 L',
  'Real Guava Vitamin Boost Juice 1 l': 'റിയൽ പേരയ്ക്ക ജ്യൂസ് 1 L',
  'Real Juice - Fruit Power, Apple 1 L': 'റിയൽ ആപ്പിൾ ജ്യൂസ് 1 L',
  'Real Juice - Fruit Power, Grape 1 L': 'റിയൽ മുന്തിരി ജ്യൂസ് 1 L',
  'Real Juice - Fruit Power, Mixed Fruits 1 L': 'റിയൽ മിക്സഡ് ഫ്രൂട്ട് ജ്യൂസ് 1 L',
  'Real Juice - Fruit Power, Orange/Santra 1 L': 'റിയൽ ഓറഞ്ച് ജ്യൂസ് 1 L',
  'Real Juice - Fruit Power, Pineapple 1 L': 'റിയൽ പൈനാപ്പിൾ ജ്യൂസ് 1 L',
  'Real Mixed Fruit Juice 1 l': 'റിയൽ മിക്സഡ് ഫ്രൂട്ട് ജ്യൂസ് 1 L',
  'Tropicana Guava Delight 1 L Pouch': 'ട്രോപ്പിക്കാന പേരയ്ക്ക ജ്യൂസ് 1 L',
  'Tropicana Mixed Fruit 1 L Pouch': 'ട്രോപ്പിക്കാന മിക്സഡ് ഫ്രൂട്ട് ജ്യൂസ് 1 L',
  'Tropicana Pomegranate 1 L pouch': 'ട്രോപ്പിക്കാന മാതളനാരങ്ങ ജ്യൂസ് 1 L',
  'Tropicana Slice Mango 600 ml': 'ട്രോപ്പിക്കാന സ്ലൈസ് മാമ്പഴ ജ്യൂസ് 600ml',
  'Tropicano Slice Mango 1.2 L': 'ട്രോപ്പിക്കാന സ്ലൈസ് മാമ്പഴ ജ്യൂസ് 1.2 L',
  'Britannia Toastea Premium Bake Rusk, 183g': 'ബ്രിട്ടാനിയ റസ്ക് 183g',
  'Britannia Toastea Premium Bake Rusk, 275g': 'ബ്രിട്ടാനിയ റസ്ക് 275g',
};

async function main() {
  console.log('🚀 Starting Kerala Malayalam Product Names migration...');
  const client = await pool.connect();
  try {
    let updatedCount = 0;
    let skippedCount = 0;

    // Fetch all products
    const res = await client.query('SELECT id, name, category_id, nutritional_note FROM products');
    console.log(`Found ${res.rows.length} total products.`);

    for (const prod of res.rows) {
      let targetName: string | null = null;
      const originalName = prod.name.trim();

      // 1. Exact match in our comprehensive dictionary
      if (KERALA_MALAYALAM_TRANSLATIONS[originalName]) {
        targetName = KERALA_MALAYALAM_TRANSLATIONS[originalName];
      } else {
        // 2. Normalize and check for common vegetable/fruit prefixes
        let clean = originalName
          .replace(/^Veg\s+/i, '')
          .replace(/^VEG\s+/i, '')
          .replace(/^Fresh\s+/i, '')
          .trim();

        if (KERALA_MALAYALAM_TRANSLATIONS[clean]) {
          targetName = KERALA_MALAYALAM_TRANSLATIONS[clean];
        } else if (KERALA_MALAYALAM_TRANSLATIONS[`Veg ${clean}`]) {
          targetName = KERALA_MALAYALAM_TRANSLATIONS[`Veg ${clean}`];
        }
      }

      if (targetName && targetName !== originalName) {
        // Update product name to Malayalam, and keep original English name in nutritional_note for easy bilingual search
        const englishNote = prod.nutritional_note ? `${originalName} | ${prod.nutritional_note}` : originalName;

        await client.query(
          'UPDATE products SET name = $1, nutritional_note = $2, last_updated = $3 WHERE id = $4',
          [targetName, englishNote, new Date().toISOString(), prod.id]
        );
        updatedCount++;
      } else {
        skippedCount++;
      }
    }

    console.log(`✅ Migration complete! Updated ${updatedCount} products to Malayalam. Skipped/Unchanged ${skippedCount}.`);
  } finally {
    client.release();
    pool.end();
  }
}

main().catch((err) => {
  console.error('Fatal migration error:', err);
  process.exit(1);
});
